name: CI

on:
    push:
        branches: master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: "Setup Node"
              with:
                  node-version: "16"
                  cache: "yarn"

            - name: "Install Dependencies"
              run: yarn --immutable

            - name: "Build"
              run: yarn build
